name 'pagekit'
maintainer 'Leonard TAVAE'
maintainer_email 'leonard.tavae@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures Pagekit'
long_description 'Installs/Configures Pagekit'
version '0.1.0'

depends 'apache2'
depends 'mysql'
depends 'database'
depends 'composer'
